/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE actorBaseService PLEASE EDIT ../actor.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Actor } from '../../domain/manage_film_example_db/actor';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Actor.service.ts
 */

/*
 * SCHEMA DB Actor
 *
	{
		birthDate: {
			type: 'Date'
		},
		name: {
			type: 'String',
			required : true
		},
		surname: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		cast: [{
			type: Schema.ObjectId,
			ref : "Film"
		}],
	}
 *
 */
@Injectable()
export class ActorBaseService {

    private actorCollection: AngularFirestoreCollection<Actor>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.actorCollection = afs.collection<Actor>('actor');
    }


    // CRUD METHODS

    /**
    * ActorService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Actor): Promise<DocumentReference> {
        return this.actorCollection.add(item);
    }

    /**
    * ActorService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.actorCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * ActorService.get
    *   @description CRUD ACTION get
    *   @param String id Id Actor
    *
    */
    get(id: string): AngularFirestoreDocument<Actor> {
        return this.afs.doc<Actor>('actor/' + id);
    }

    /**
    * ActorService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Actor[]> {
        return this.afs.collection('actor').snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Actor;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * ActorService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(itemDoc: AngularFirestoreDocument<Actor>, item: Actor): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs

}
