/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE film-makerBaseService PLEASE EDIT ../film-maker.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { FilmMaker } from '../../domain/manage_film_example_db/film-maker';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../FilmMaker.service.ts
 */

/*
 * SCHEMA DB FilmMaker
 *
	{
		name: {
			type: 'String',
			required : true
		},
		surname: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		filmMaker: {
			type: Schema.ObjectId,
			required : true,
			ref : "Film"
		},
	}
 *
 */
@Injectable()
export class FilmMakerBaseService {

    private filmmakerCollection: AngularFirestoreCollection<FilmMaker>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.filmmakerCollection = afs.collection<FilmMaker>('filmmaker');
    }


    // CRUD METHODS

    /**
    * FilmMakerService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: FilmMaker): Promise<DocumentReference> {
        return this.filmmakerCollection.add(item);
    }

    /**
    * FilmMakerService.delete
    *   @description CRUD ACTION delete
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.filmmakerCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * FilmMakerService.get
    *   @description CRUD ACTION get
    *
    */
    get(id: string): AngularFirestoreDocument<FilmMaker> {
        return this.afs.doc<FilmMaker>('filmmaker/' + id);
    }

    /**
    * FilmMakerService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<FilmMaker[]> {
        return this.afs.collection('filmmaker').snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as FilmMaker;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * FilmMakerService.update
    *   @description CRUD ACTION update
    *
    */
    update(itemDoc: AngularFirestoreDocument<FilmMaker>, item: FilmMaker): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs

}
