/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE filmBaseService PLEASE EDIT ../film.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Film } from '../../domain/manage_film_example_db/film';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Film.service.ts
 */

/*
 * SCHEMA DB Film
 *
	{
		genre: {
			type: 'String',
			enum : ["Action","Crime","Fantasy","Horror"]
		},
		title: {
			type: 'String',
			required : true
		},
		year: {
			type: 'Number'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		cast: [{
			type: Schema.ObjectId,
			ref : "Film"
		}],
		filmMaker: {
			type: Schema.ObjectId,
			required : true,
			ref : "Film"
		},
	}
 *
 */
@Injectable()
export class FilmBaseService {

    private filmCollection: AngularFirestoreCollection<Film>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.filmCollection = afs.collection<Film>('film');
    }


    // CRUD METHODS

    /**
    * FilmService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Film): Promise<DocumentReference> {
        return this.filmCollection.add(item);
    }

    /**
    * FilmService.delete
    *   @description CRUD ACTION delete
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.filmCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * FilmService.findBycast
    *   @description CRUD ACTION findBycast
    *
    */
    findByCast(id: string): Observable<any[]> {
        return this.afs.collection('film', ref => ref.where('cast', 'array-contains', id)).snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Film;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * FilmService.findByfilmMaker
    *   @description CRUD ACTION findByfilmMaker
    *
    */
    findByFilmMaker(id: string): Observable<any[]> {
        return this.afs.collection('film', ref => ref.where('filmMaker', '==', id)).snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Film;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * FilmService.get
    *   @description CRUD ACTION get
    *
    */
    get(id: string): AngularFirestoreDocument<Film> {
        return this.afs.doc<Film>('film/' + id);
    }

    /**
    * FilmService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Film[]> {
        return this.afs.collection('film').snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Film;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * FilmService.update
    *   @description CRUD ACTION update
    *
    */
    update(itemDoc: AngularFirestoreDocument<Film>, item: Film): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs


    /**
    * FilmService.myfunction
    *   @description custom function example
    *   @param String param1 fn param
    *   @param Number param2 fn param 2
    *   @returns String
    *
    */
    myfunction(...params: any[]): Observable<any> {
        const callable = this.fns.httpsCallable('myfunction');
        return callable(params);
    }

}
